    document.write("<header>")
    document.write("<a href='./inicial.html'>")
    document.write("<img class='logo' src='./imagem/logo.png' width='170px' height='170px' alt='logo'>")
    document.write("</a>")
    document.write("<a href='./inicial.html'>")
    document.write("<h2>KARINA MOREIRA CUSTODIO</h2>")
    document.write("</a>")
    document.write("</header>")